### ISSUE TITLE
Namespace error from 06_1DFFT_reuse_plans.cpp example

### ISSUE THREAD

**Issue by W-Wuxian** [kokkos/kokkos-fft#221]
Trying to compile a KokkosFFT Plan example based on example 06_1DFFT_reuse_plans.cpp, I got the following Error:
```bash
DEMO-KOKKOS/kokkos-fft/T.cpp(34): error: namespace "KokkosFFT" has no member "Plan"
      KokkosFFT::Plan fft_plan(exec, xc2c, xc2c_hat, KokkosFFT::Direction::forward, axis);
DEMO-KOKKOS/kokkos-fft/T.cpp(37): error: namespace "KokkosFFT" has no member "Plan"
      KokkosFFT::Plan ifft_plan(exec, xc2c_hat, xc2c_inv,
DEMO-KOKKOS/kokkos-fft/T.cpp(46): error: namespace "KokkosFFT" has no member "Plan"
      KokkosFFT::Plan rfft_plan(exec, xr2c, xr2c_hat,   
DEMO-KOKKOS/kokkos-fft/T.cpp(55): error: namespace "KokkosFFT" has no member "Plan"
      KokkosFFT::Plan irfft_plan(exec, xc2r, xc2r_hat,
```
see attached md file for more details (cmake, make log files, software version...)

[kokko-fftw-error.md](https://github.com/user-attachments/files/18494690/kokko-fftw-error.md)

**Comment by yasahi-hpc** [comment]
Hi, we have moved `KokkosFFT::Impl::Plan` to `KokkosFFT::Plan` after 0.2.1 release. I am considering to release 0.3.0 after merging current PRs. As requested by core team, the `Plan` API may be changed in the future (see [#200](https://github.com/kokkos/kokkos-fft/issues/200)).

The `Plan` APIs at 0.2.1 are found at https://github.com/kokkos/kokkos-fft/blob/v0.2.1/examples/06_1DFFT_reuse_plans/06_1DFFT_reuse_plans.cpp

By the way, Kokkos no longer supports nvhpc as a CUDA device compiler after 4.4 (https://github.com/kokkos/kokkos/pull/6987).

**Comment by W-Wuxian** [comment]
- seems good with The Plan APIs at 0.2.1 !
- Regarding support of nvhpc  as compiler, should I recompile kokkos with the following:
```bash
-DCMAKE_CXX_COMPILER=g++ # instead of nvc++
```

**Comment by yasahi-hpc** [comment]
Nice to hear that it works with 0.2.1 style. 

For the second point, I would recommend to recompile with g++.
Since it is not officially supported, we may encounter unexpected issues

**Comment by yasahi-hpc** [comment]
Sorry I might be wrong. If you are using `nvhpc` as a host compiler, it is still valid. If this is the case for you (and probably is), you can still use it as is.
